# Generated by Django 5.1.2 on 2024-11-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='wrapped',
            name='reccomended_songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wrapped',
            name='recomended_songs',
            field=models.ManyToManyField(related_name='recomended_songs', to='home.song'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='icon_href',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='icon_href',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='topartistrel',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='topsongrel',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='TopWeeklyArtistRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=-1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.artist')),
                ('wrapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wrapped')),
            ],
        ),
        migrations.AddField(
            model_name='wrapped',
            name='top_weekly_artists',
            field=models.ManyToManyField(related_name='top_weekly_artists', through='home.TopWeeklyArtistRel', to='home.artist'),
        ),
        migrations.CreateModel(
            name='TopWeeklySongRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=-1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.song')),
                ('wrapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wrapped')),
            ],
        ),
        migrations.AddField(
            model_name='wrapped',
            name='top_weekly_songs',
            field=models.ManyToManyField(related_name='top_weekly_songs', through='home.TopWeeklySongRel', to='home.song'),
        ),
    ]
